"""empty message

Revision ID: 1172aeecdb0
Revises: 2acdbadb1c22
Create Date: 2015-02-16 22:56:25.955354

"""

# revision identifiers, used by Alembic.
revision = '1172aeecdb0'
down_revision = '2acdbadb1c22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streamer', sa.Column('youtube_name', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streamer', 'youtube_name')
    ### end Alembic commands ###
