"""empty message

Revision ID: 14bb1343f5dc
Revises: 15119ab3dc68
Create Date: 2015-04-06 01:26:26.626951

"""

# revision identifiers, used by Alembic.
revision = '14bb1343f5dc'
down_revision = '15119ab3dc68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_on', sa.DateTime(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    ### end Alembic commands ###
