"""empty message

Revision ID: 15119ab3dc68
Revises: 3c85ad888187
Create Date: 2015-04-03 01:32:25.349587

"""

# revision identifiers, used by Alembic.
revision = '15119ab3dc68'
down_revision = '3c85ad888187'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idea')
    ### end Alembic commands ###
