"""empty message

Revision ID: 177b55430b61
Revises: None
Create Date: 2015-01-29 22:29:18.963249

"""

# revision identifiers, used by Alembic.
revision = '177b55430b61'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream')
    ### end Alembic commands ###
