"""empty message

Revision ID: 186a4a79b60e
Revises: 4a6b015f38b7
Create Date: 2015-03-15 14:41:09.104730

"""

# revision identifiers, used by Alembic.
revision = '186a4a79b60e'
down_revision = '4a6b015f38b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('confstream', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream', 'confstream')
    ### end Alembic commands ###
