"""empty message

Revision ID: 189d203be5f7
Revises: 409e5de344f7
Create Date: 2015-04-22 22:48:22.690788

"""

# revision identifiers, used by Alembic.
revision = '189d203be5f7'
down_revision = '409e5de344f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
