"""empty message

Revision ID: 19f4bcad6f39
Revises: 59264050f39
Create Date: 2015-02-05 17:09:54.075699

"""

# revision identifiers, used by Alembic.
revision = '19f4bcad6f39'
down_revision = '59264050f39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('last_time_live', sa.DateTime(), nullable=True))
    op.add_column('stream', sa.Column('submission_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream', 'submission_id')
    op.drop_column('stream', 'last_time_live')
    ### end Alembic commands ###
