"""empty message

Revision ID: 1aaef862b2da
Revises: 177b55430b61
Create Date: 2015-01-30 01:09:41.117541

"""

# revision identifiers, used by Alembic.
revision = '1aaef862b2da'
down_revision = '177b55430b61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('channel', sa.String(length=25), nullable=False))
    op.add_column('stream', sa.Column('ytid', sa.String(length=11), nullable=False))
    op.create_unique_constraint(None, 'stream', ['channel'])
    op.create_unique_constraint(None, 'stream', ['ytid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stream', type_='unique')
    op.drop_constraint(None, 'stream', type_='unique')
    op.drop_column('stream', 'ytid')
    op.drop_column('stream', 'channel')
    ### end Alembic commands ###
