"""empty message

Revision ID: 1f8165cd3c06
Revises: 56da2beefa69
Create Date: 2015-02-22 16:04:09.297033

"""

# revision identifiers, used by Alembic.
revision = '1f8165cd3c06'
down_revision = '56da2beefa69'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subscriber_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], [u'stream.id'], name=u'subscription_stream_id_fkey'),
    sa.ForeignKeyConstraint(['subscriber_id'], [u'subscriber.id'], name=u'subscription_subscriber_id_fkey')
    )
    ### end Alembic commands ###
