"""empty message

Revision ID: 2034a187fa21
Revises: 55db74dd77fb
Create Date: 2015-05-22 17:17:50.880585

"""

# revision identifiers, used by Alembic.
revision = '2034a187fa21'
down_revision = '55db74dd77fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streamer', sa.Column('banned', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streamer', 'banned')
    ### end Alembic commands ###
