"""empty message

Revision ID: 248ae2bc590e
Revises: 440bcc45ff09
Create Date: 2015-04-22 22:40:56.994738

"""

# revision identifiers, used by Alembic.
revision = '248ae2bc590e'
down_revision = '440bcc45ff09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streamer_subscriptions',
    sa.Column('streamer_id', sa.Integer(), nullable=True),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['streamer_id'], ['streamer.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscriber.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streamer_subscriptions')
    ### end Alembic commands ###
