"""empty message

Revision ID: 28af272381c0
Revises: 506670dd498b
Create Date: 2015-02-02 21:58:49.933618

"""

# revision identifiers, used by Alembic.
revision = '28af272381c0'
down_revision = '506670dd498b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE stream_status AS ENUM ('upcoming', 'live', 'completed')")
    op.add_column('stream', sa.Column('status', sa.Enum('upcoming', 'live', 'completed', name='stream_status'), nullable=True))
    op.drop_column('stream', 'is_live')
    op.drop_column('stream', 'is_completed')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE stream_status")
    op.add_column('stream', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('stream', sa.Column('is_live', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('stream', 'status')
    ### end Alembic commands ###
