"""empty message

Revision ID: 2acdbadb1c22
Revises: 40ee5ffde5ae
Create Date: 2015-02-16 18:17:42.833869

"""

# revision identifiers, used by Alembic.
revision = '2acdbadb1c22'
down_revision = '40ee5ffde5ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream', 'submission_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('submission_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
