"""empty message

Revision ID: 2f8bfdb8907a
Revises: 1aaef862b2da
Create Date: 2015-01-30 01:12:11.716491

"""

# revision identifiers, used by Alembic.
revision = '2f8bfdb8907a'
down_revision = '1aaef862b2da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stream', 'channel',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.alter_column('stream', 'ytid',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stream', 'ytid',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('stream', 'channel',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    ### end Alembic commands ###
