"""empty message

Revision ID: 321abb98221b
Revises: 37bf6149a5af
Create Date: 2015-07-08 20:56:33.277708

"""

# revision identifiers, used by Alembic.
revision = '321abb98221b'
down_revision = '37bf6149a5af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('streamer', 'banned', new_column_name='is_banned')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('streamer', 'is_banned', new_column_name='banned')
    ### end Alembic commands ###
