"""empty message

Revision ID: 35bd36f44f4
Revises: 25534835d187
Create Date: 2015-03-26 01:23:00.449660

"""

# revision identifiers, used by Alembic.
revision = '35bd36f44f4'
down_revision = '25534835d187'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('rtmp_secret', sa.String(length=50), nullable=True))
    op.drop_column('stream', 'rtmp_key')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('rtmp_key', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('stream', 'rtmp_secret')
    ### end Alembic commands ###
