"""empty message

Revision ID: 37bf6149a5af
Revises: 33dc40a1e6b3
Create Date: 2015-06-19 23:03:16.508567

"""

# revision identifiers, used by Alembic.
revision = '37bf6149a5af'
down_revision = '33dc40a1e6b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('vod_views', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream', 'vod_views')
    ### end Alembic commands ###
