"""empty message

Revision ID: 394f85935d21
Revises: 186a4a79b60e
Create Date: 2015-03-20 20:21:01.792691

"""

# revision identifiers, used by Alembic.
revision = '394f85935d21'
down_revision = '186a4a79b60e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wpc_stream',
    sa.Column('path', sa.String(length=30), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('path')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wpc_stream')
    ### end Alembic commands ###
