"""empty message

Revision ID: 3a7cac1b3adc
Revises: 4691e59fa601
Create Date: 2015-03-22 23:44:54.269041

"""

# revision identifiers, used by Alembic.
revision = '3a7cac1b3adc'
down_revision = '4691e59fa601'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream', 'viewer_num')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('viewer_num', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
