"""empty message

Revision ID: 3acbc54c61e5
Revises: 14bb1343f5dc
Create Date: 2015-04-06 01:50:55.193428

"""

# revision identifiers, used by Alembic.
revision = '3acbc54c61e5'
down_revision = '14bb1343f5dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('streamer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_message', 'streamer', ['streamer_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_column('chat_message', 'streamer_id')
    ### end Alembic commands ###
