"""empty message

Revision ID: 3c85ad888187
Revises: 59de59c96978
Create Date: 2015-03-29 21:53:00.500655

"""

# revision identifiers, used by Alembic.
revision = '3c85ad888187'
down_revision = '59de59c96978'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('recording_available', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'recording_available')
    ### end Alembic commands ###
