"""empty message

Revision ID: 3edb1dee1de2
Revises: dc0fb05d464
Create Date: 2015-02-26 01:23:00.110823

"""

# revision identifiers, used by Alembic.
revision = '3edb1dee1de2'
down_revision = 'dc0fb05d464'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('stream_tag',
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('tag_name', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.ForeignKeyConstraint(['tag_name'], ['tag.name'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream_tag')
    op.drop_table('tag')
    ### end Alembic commands ###
