"""empty message

Revision ID: 409e5de344f7
Revises: 248ae2bc590e
Create Date: 2015-04-22 22:46:56.510912

"""

# revision identifiers, used by Alembic.
revision = '409e5de344f7'
down_revision = '248ae2bc590e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
