"""empty message

Revision ID: 40ee5ffde5ae
Revises: 8b477c4e904
Create Date: 2015-02-16 00:23:02.271007

"""

# revision identifiers, used by Alembic.
revision = '40ee5ffde5ae'
down_revision = '8b477c4e904'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('actual_start_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream', 'actual_start_time')
    ### end Alembic commands ###
