"""empty message

Revision ID: 440bcc45ff09
Revises: a147591613
Create Date: 2015-04-20 18:54:51.829730

"""

# revision identifiers, used by Alembic.
revision = '440bcc45ff09'
down_revision = 'a147591613'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streamer', sa.Column('as_subscriber_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'streamer', 'subscriber', ['as_subscriber_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'streamer', type_='foreignkey')
    op.drop_column('streamer', 'as_subscriber_id')
    ### end Alembic commands ###
