"""empty message

Revision ID: 44c3becf9745
Revises: 34d183116728
Create Date: 2015-02-01 17:18:35.172244

"""

# revision identifiers, used by Alembic.
revision = '44c3becf9745'
down_revision = '34d183116728'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('stream', sa.Column('is_live', sa.Boolean(), nullable=True))
    op.add_column('stream', sa.Column('schelduled_start_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream', 'schelduled_start_time')
    op.drop_column('stream', 'is_live')
    op.drop_column('stream', 'is_completed')
    ### end Alembic commands ###
