"""empty message

Revision ID: 4691e59fa601
Revises: 394f85935d21
Create Date: 2015-03-22 20:03:37.879054

"""

# revision identifiers, used by Alembic.
revision = '4691e59fa601'
down_revision = '394f85935d21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wpc_stream')
    op.add_column('stream', sa.Column('channel_name', sa.String(length=30), nullable=True))
    op.add_column('stream', sa.Column('viewer_num', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'stream', ['channel_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stream', type_='unique')
    op.drop_column('stream', 'viewer_num')
    op.drop_column('stream', 'channel_name')
    op.create_table('wpc_stream',
    sa.Column('path', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('is_live', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('path', name=u'wpc_stream_pkey')
    )
    ### end Alembic commands ###
