"""empty message

Revision ID: 4a6b015f38b7
Revises: 3edb1dee1de2
Create Date: 2015-03-07 21:16:28.821959

"""

# revision identifiers, used by Alembic.
revision = '4a6b015f38b7'
down_revision = '3edb1dee1de2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('current_viewers', sa.Integer()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream', 'current_viewers')
    ### end Alembic commands ###
