"""empty message

Revision ID: 506670dd498b
Revises: 44c3becf9745
Create Date: 2015-02-01 17:39:57.317860

"""

# revision identifiers, used by Alembic.
revision = '506670dd498b'
down_revision = '44c3becf9745'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('scheduled_start_time', sa.DateTime(), nullable=True))
    op.drop_column('stream', 'schelduled_start_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('schelduled_start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('stream', 'scheduled_start_time')
    ### end Alembic commands ###
