"""empty message

Revision ID: 53f873e5917f
Revises: 1f8165cd3c06
Create Date: 2015-02-22 16:35:08.579471

"""

# revision identifiers, used by Alembic.
revision = '53f873e5917f'
down_revision = '1f8165cd3c06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stream', ['channel'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stream', type_='unique')
    ### end Alembic commands ###
