"""empty message

Revision ID: 552800b5e708
Revises: 321abb98221b
Create Date: 2015-07-09 19:56:38.087576

"""

# revision identifiers, used by Alembic.
revision = '552800b5e708'
down_revision = '321abb98221b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('stream_sub', 'stream_submission')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('stream_submission', 'stream_sub')
    ### end Alembic commands ###
