"""empty message

Revision ID: 55db74dd77fb
Revises: 5298543c9ff7
Create Date: 2015-05-14 18:30:36.605244

"""

# revision identifiers, used by Alembic.
revision = '55db74dd77fb'
down_revision = '5298543c9ff7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streamer', sa.Column('last_time_notified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streamer', 'last_time_notified')
    ### end Alembic commands ###
