"""empty message

Revision ID: 56da2beefa69
Revises: 1172aeecdb0
Create Date: 2015-02-19 18:20:51.474596

"""

# revision identifiers, used by Alembic.
revision = '56da2beefa69'
down_revision = '1172aeecdb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streamer', sa.Column('info', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streamer', 'info')
    ### end Alembic commands ###
