"""empty message

Revision ID: 59264050f39
Revises: 20e031b23d18
Create Date: 2015-02-04 17:18:39.703657

"""

# revision identifiers, used by Alembic.
revision = '59264050f39'
down_revision = '20e031b23d18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('title', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream', 'title')
    ### end Alembic commands ###
