"""empty message

Revision ID: 59de59c96978
Revises: 35bd36f44f4
Create Date: 2015-03-26 01:27:39.100789

"""

# revision identifiers, used by Alembic.
revision = '59de59c96978'
down_revision = '35bd36f44f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream', 'rtmp_secret')
    op.add_column('streamer', sa.Column('rtmp_secret', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streamer', 'rtmp_secret')
    op.add_column('stream', sa.Column('rtmp_secret', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    ### end Alembic commands ###
