"""empty message

Revision ID: 8b477c4e904
Revises: 6ae3f450df3
Create Date: 2015-02-12 21:16:15.970509

"""

# revision identifiers, used by Alembic.
revision = '8b477c4e904'
down_revision = '6ae3f450df3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('submission_id', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('stream_sub',
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('submission_id', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.submission_id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream_sub')
    op.drop_table('submission')
    ### end Alembic commands ###
