"""empty message

Revision ID: a147591613
Revises: c15d1c33
Create Date: 2015-04-20 18:52:19.694648

"""

# revision identifiers, used by Alembic.
revision = 'a147591613'
down_revision = 'c15d1c33'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
