"""empty message

Revision ID: c15d1c33
Revises: 45fdcd9ac732
Create Date: 2015-04-17 22:00:04.989871

"""

# revision identifiers, used by Alembic.
revision = 'c15d1c33'
down_revision = '45fdcd9ac732'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streamer', sa.Column('rtmp_redirect_1', sa.String(), nullable=True))
    op.add_column('streamer', sa.Column('rtmp_redirect_2', sa.String(), nullable=True))
    op.add_column('streamer', sa.Column('rtmp_redirect_3', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streamer', 'rtmp_redirect_3')
    op.drop_column('streamer', 'rtmp_redirect_2')
    op.drop_column('streamer', 'rtmp_redirect_1')
    ### end Alembic commands ###
