"""empty message

Revision ID: c4d9324867c
Revises: 2034a187fa21
Create Date: 2015-05-22 18:10:31.306344

"""

# revision identifiers, used by Alembic.
revision = 'c4d9324867c'
down_revision = '2034a187fa21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream', sa.Column('chat_anon_forbidden', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream', 'chat_anon_forbidden')
    ### end Alembic commands ###
