"""empty message

Revision ID: dc0fb05d464
Revises: 53f873e5917f
Create Date: 2015-02-24 01:43:53.833937

"""

# revision identifiers, used by Alembic.
revision = 'dc0fb05d464'
down_revision = '53f873e5917f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streamer', sa.Column('checked', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streamer', 'checked')
    ### end Alembic commands ###
