"""empty message

Revision ID: ebb0ebbae03
Revises: 19f4bcad6f39
Create Date: 2015-02-10 23:29:31.898948

"""

# revision identifiers, used by Alembic.
revision = 'ebb0ebbae03'
down_revision = '19f4bcad6f39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stream', 'title', type_=sa.String(200), existing_type=sa.String(length=100), nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stream', 'title', type_=sa.String(100), existing_type=sa.String(length=200), nullable=True)
    ### end Alembic commands ###
