"""empty message

Revision ID: ebb0ebbae03
Revises: 19f4bcad6f39
Create Date: 2015-02-10 23:29:31.898948

"""

# revision identifiers, used by Alembic.
revision = 'ebb0ebbae03'
down_revision = '19f4bcad6f39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
