"""empty message

Revision ID: f3488b67bc7
Revises: 189d203be5f7
Create Date: 2015-04-27 22:49:43.805548

"""

# revision identifiers, used by Alembic.
revision = 'f3488b67bc7'
down_revision = '189d203be5f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
